# -*- coding: utf-8 -*-
"""cv lab 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1topQsBqbifPAnJBO98f7GptGPnhHs59l
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

def show_comparison(original,sobel,prewitt,canny):
  plt.figure(figsize=(12,10))
  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title('Original Grayscale Image')
  plt.axis('off')
  plt.subplot(2,2,2)
  plt.imshow(sobel,cmap='gray')
  plt.title('Sobel Edge Detection')
  plt.axis('off')
  plt.subplot(2,2,3)
  plt.imshow(prewitt,cmap='gray')
  plt.title('Prewitt Edge Detection')
  plt.axis('off')
  plt.subplot(2,2,4)
  plt.imshow(canny,cmap='gray')
  plt.title('Candy Edge Detection')
  plt.axis('off')
  plt.tight_layout()
  plt.show()

#read an image
image = cv2.imread('/content/shinchan',0)
if image is None:
  print('Error loading image')
else:
  #sobel operation
  #gradient in x&y direction
  sobelx=cv2.Sobel(image,cv2.CV_64F,1,0,ksize=3)
  sobely=cv2.Sobel(image,cv2.CV_64F,0,1,ksize=3)
  #combine gradients
  sobel_combine=cv2.magnitude(sobelx,sobely)
  #prewitt operation
  kanelx=np.array(([1,1,1],[0,0,0],[-1,-1,-1]))
  kanely=np.array(([-1,0,1],[-1,0,1],[-1,0,1]))
  #apply kernels using filter 2D
  prewittx=cv2.filter2D(image,-1,kanelx)
  prewitty=cv2.filter2D(image,-1,kanely)
  prewitt_combine=prewittx+prewitty
  #candy edge detection
  #arguments:image,threshhold1.threshhold2
  candy_edges=cv2.Canny(image,100,200)
  #display results
  show_comparison(image,sobel_combine,prewitt_combine,candy_edges)